# Makefile

all:			semaphore.tin crossroad.tin advanced_crossroad.tin tinybenchmark.tin benchmark.tin benchmark_8.tin benchmark_16.tin enterprise.tin excl.tin mutex_4.tin resource.tin multiplexer.tin cs.tin wm.tin outchar.tin blanket.tin parbench.tin

semaphore.tin:		semaphore.btl
			ting -o semaphore.tin semaphore.btl

crossroad.tin:		crossroad.btl
			ting -o crossroad.tin crossroad.btl

advanced_crossroad.tin:	advanced_crossroad.btl
			ting -o advanced_crossroad.tin advanced_crossroad.btl

tinybenchmark.tin:	tinybenchmark.btl
			ting -o tinybenchmark.tin tinybenchmark.btl

benchmark.tin:		benchmark.btl
			ting -o benchmark.tin benchmark.btl

benchmark_8.tin:	benchmark_8.btl
			ting -o benchmark_8.tin benchmark_8.btl

benchmark_16.tin:	benchmark_16.btl
			ting -o benchmark_16.tin benchmark_16.btl

enterprise.tin:		enterprise.btl
			ting -o enterprise.tin enterprise.btl

excl.tin:		excl.btl
			ting -o excl.tin excl.btl

mutex_4.tin:		mutex_4.btl
			ting -o mutex_4.tin mutex_4.btl

resource.tin:		resource.btl
			ting -o resource.tin resource.btl

multiplexer.tin:	multiplexer.btl
			ting -o multiplexer.tin multiplexer.btl

cs.tin:			cs.btl
			ting -o cs.tin cs.btl

wm.tin:			wm.btl
			ting -o wm.tin wm.btl

outchar.tin:		outchar.btl
			ting -o outchar.tin outchar.btl

blanket.tin:		blanket.btl
			ting -o blanket.tin blanket.btl

parbench.tin:		parbench.btl
			ting -o parbench.tin parbench.btl
clean:
			rm -f *.tin *.evl *~

