# Makefile

all:			semaphore.tin crossroad.tin advanced_crossroad.tin tinybenchmark.tin benchmark.tin benchmark_8.tin benchmark_16.tin enterprise.tin excl.tin mutex_4.tin resource.tin

semaphore.tin:		semaphore.btl
			ting -o semaphore.tin semaphore.btl

crossroad.tin:		crossroad.btl
			ting -o crossroad.tin crossroad.btl

advanced_crossroad.tin:	advanced_crossroad.btl
			ting -o advanced_crossroad.tin advanced_crossroad.btl

tinybenchmark.tin:		tinybenchmark.btl
			ting -o tinybenchmark.tin tinybenchmark.btl

benchmark.tin:		benchmark.btl
			ting -o benchmark.tin benchmark.btl

benchmark_8.tin:	benchmark_8.btl
			ting -o benchmark_8.tin benchmark_8.btl

benchmark_16.tin:	benchmark_16.btl
			ting -o benchmark_16.tin benchmark_16.btl

enterprise.tin:		enterprise.btl
			ting -o enterprise.tin enterprise.btl

excl.tin:		excl.btl
			ting -o excl.tin excl.btl

mutex_4.tin:		mutex_4.btl
			ting -o mutex_4.tin mutex_4.btl

resource.tin:		resource.btl
			ting -o resource.tin resource.btl
clean:
			rm -f *.tin *.evl *~

